name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)
    paths:
      - 'supabase/functions/**' # Trigger only when function code changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a Node.js version compatible with Supabase CLI

      - name: Install Supabase CLI (Specific Version)
        # Install a specific, newer version of Supabase CLI that supports 'pull'
        run: npm install supabase@1.77.0 # <--- THIS LINE IS CRITICAL
        working-directory: ./supabase # Install it into the 'supabase' directory

      - name: Initialize Supabase Project
        # This creates the supabase/config.toml and other boilerplate if it doesn't exist.
        # It's crucial to run this FIRST if config.toml is missing.
        run: npx supabase init
        working-directory: ./supabase # Run init inside the 'supabase' directory

      - name: Link Supabase Project
        # This updates the newly created/existing supabase/config.toml with the project ref
        run: npx supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        working-directory: ./supabase # Link command runs from 'supabase' directory
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Pull Supabase Configuration
        # Pulls remote config into local files, helping with consistency warnings and function sync.
        # This step should now work since 'init' created config.toml.
        run: npx supabase pull
        working-directory: ./supabase # Pull command runs from 'supabase' directory
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy upload-to-drive function
        # Now explicitly tell it the config file location
        run: npx supabase functions deploy upload-to-drive --no-verify-jwt --config ./supabase/config.toml
        # Ensure 'working-directory: ./supabase' is NOT present here for the deploy command itself,
        # as the path is relative to the repo root.
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }} # Confirmed this matches your index.ts
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
