name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)
    paths:
      - 'supabase/functions/**' # Trigger only when function code changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a Node.js version compatible with Supabase CLI

      - name: Install Supabase CLI (Specific Version)
        # Install a specific, newer version of Supabase CLI
        run: npm install supabase@1.77.0
        working-directory: ./supabase # Install it into the 'supabase' directory

      - name: Initialize Supabase Project
        # This creates the supabase/config.toml and other boilerplate if it doesn't exist.
        run: ./supabase/node_modules/.bin/supabase init
        working-directory: ./ # Run from repo root

      - name: Link Supabase Project
        # This updates the newly created/existing supabase/config.toml with the project ref
        run: ./supabase/node_modules/.bin/supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        working-directory: ./ # Run from repo root
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      # - name: Pull Supabase Configuration
      #   # Temporarily disabled due to "unknown command" error.
      #   # Will re-enable or debug separately if needed after deployment works.
      #   run: ./supabase/node_modules/.bin/supabase pull
      #   working-directory: ./ # Run from repo root
      #   env:
      #     SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy upload-to-drive function
        # Using --workdir to specify the supabase project directory
        run: ./supabase/node_modules/.bin/supabase --workdir ./supabase functions deploy upload-to-drive --no-verify-jwt
        working-directory: ./ # Run from repo root
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
