name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)
    paths:
      - 'supabase/functions/**' # Trigger only when function code changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a Node.js version compatible with Supabase CLI

      - name: Install Supabase CLI
        run: npm install -g supabase@latest # Installs Supabase CLI globally

      - name: Link Supabase Project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} # CORRECTED LINE: reference the secret
        working-directory: ./supabase # Run this command from the 'supabase' directory
        env: # Add this env block for the link step
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }} # Needed for authentication during linking

      - name: Deploy upload-to-drive function
        run: supabase functions deploy upload-to-drive --no-verify-jwt # Deploy the function
        working-directory: ./supabase # Run this command from the 'supabase' directory
        env:
          # Set Google secrets directly from GitHub Actions secrets
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          # Supabase CLI needs the access token for deployment
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
