name: Deploy Supabase Functions

on:
  push:
    branches:
      - main # Or your main branch name, e.g., master
    paths:
      - 'supabase/**' # Trigger only when changes occur in the supabase directory

jobs:
  deploy:
    runs-on: ubuntu-24.04 # Use the latest Ubuntu LTS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Or your preferred Node.js version
        working-directory: ./supabase # Run this step from the supabase directory

      - name: Install Supabase CLI
        run: npm install supabase@1.77.0 # Pin to a specific version for stability, or use latest
        working-directory: ./supabase

      - name: Supabase Init
        # This command initializes a new Supabase project or ensures the local setup is valid.
        # It creates/updates supabase/config.toml if needed.
        run: ./node_modules/.bin/supabase init
        working-directory: ./supabase

      - name: Supabase Link Project
        # Links your local Supabase project to your remote hosted project using the project ID.
        run: ./node_modules/.bin/supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }} # Required for linking
        working-directory: ./supabase

      - name: Correct functions_path in config.toml
        # This step uses `yq` to ensure functions_path is correctly set to "functions".
        # This is a robust way to edit TOML files and should override any incorrect settings
        # that might have been generated by `supabase init` or `supabase link`.
        run: yq -i '.functions.functions_path = "functions"' config.toml
        working-directory: ./supabase # Operate on config.toml inside the supabase directory

      - name: Deploy Supabase Function 'upload-to-drive'
        # Deploy your specific function.
        run: ./node_modules/.bin/supabase functions deploy upload-to-drive --no-verify-jwt
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }} # Required for deploying functions
        working-directory: ./supabase # Run this command from the supabase directory
