name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)
    paths:
      - 'supabase/functions/**' # Trigger only when function code changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a Node.js version compatible with Supabase CLI

      - name: Install Supabase CLI (Specific Version)
        # Install a specific, newer version of Supabase CLI that supports 'pull'
        run: npm install supabase@1.77.0 # Explicitly set a version that supports 'pull'
        working-directory: ./supabase # Install it where it will be used

      - name: Link Supabase Project
        # Use the locally installed CLI
        run: npx supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        working-directory: ./supabase # Link command runs from 'supabase' directory
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Pull Supabase Configuration (Now should work)
        # Pulls remote config into local files, helping with consistency warnings
        run: npx supabase pull
        working-directory: ./supabase # Pull command runs from 'supabase' directory
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy upload-to-drive function
        # Now explicitly tell it the config file location
        run: npx supabase functions deploy upload-to-drive --no-verify-jwt --config ./supabase/config.toml
        # Ensure 'working-directory: ./supabase' is NOT present here
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }} # CONFIRM THIS SECRET NAME AGAIN
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
