name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)
    paths:
      - 'supabase/functions/**' # Trigger only when function code changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a Node.js version compatible with Supabase CLI

      - name: Install Supabase CLI (Specific Version)
        # Install a specific, newer version of Supabase CLI that supports 'pull'
        run: npm install supabase@1.77.0 # This version should work
        working-directory: ./supabase # Install it into the 'supabase' directory

      - name: Initialize Supabase Project
        # This creates the supabase/config.toml and other boilerplate if it doesn't exist.
        run: ./supabase/node_modules/.bin/supabase init # Directly call the local executable
        working-directory: ./ # Run from repo root, but command refers to 'supabase' directory

      - name: Link Supabase Project
        # This updates the newly created/existing supabase/config.toml with the project ref
        run: ./supabase/node_modules/.bin/supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} # Directly call the local executable
        working-directory: ./ # Run from repo root, but command refers to 'supabase' directory
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Pull Supabase Configuration
        # Pulls remote config into local files, helping with consistency warnings and function sync.
        run: ./supabase/node_modules/.bin/supabase pull # Directly call the local executable
        working-directory: ./ # Run from repo root, but command refers to 'supabase' directory
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy upload-to-drive function
        # Deploy command from repo root, explicitly pointing to config.toml
        run: ./supabase/node_modules/.bin/supabase functions deploy upload-to-drive --no-verify-jwt --config ./supabase/config.toml
        working-directory: ./ # Run from repo root, but command refers to 'supabase' directory
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
