name: Deploy Supabase Functions

on:
  push:
    branches:
      - main # Or your main branch name, e.g., master
    paths:
      - 'supabase/**' # Trigger only when changes occur in the supabase directory

jobs:
  deploy:
    runs-on: ubuntu-24.04 # Use the latest Ubuntu LTS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Or your preferred Node.js version
        # Removed working-directory from this step
        # It's generally not needed for 'setup' actions as they configure the environment.

      - name: Install Supabase CLI
        run: npm install supabase@1.77.0 # Pin to a specific version for stability, or use latest
        working-directory: ./supabase # This is essential for npm install

      - name: Supabase Init
        run: ./node_modules/.bin/supabase init
        working-directory: ./supabase # This is essential for supabase init

      - name: Supabase Link Project
        run: ./node_modules/.bin/supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }} # Required for linking
        working-directory: ./supabase # This is essential for supabase link

      - name: Correct functions_path in config.toml
        run: yq -i '.functions.functions_path = "functions"' config.toml
        working-directory: ./supabase # This is essential for yq to find the config.toml

      - name: Deploy Supabase Function 'upload-to-drive'
        run: ./node_modules/.bin/supabase functions deploy upload-to-drive --no-verify-jwt
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }} # Required for deploying functions
        working-directory: ./supabase # This is essential for supabase functions deploy
